version: "3.8"

networks:
  bibliography-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    container_name: bibliography-db
    environment:
      POSTGRES_PASSWORD: bibliography
      POSTGRES_USER: bibliography
    volumes:
      - ./dataset/database_data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - bibliography-network
  backend:
    image: bibliography-dev-api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pdfgenerator-backend
    volumes:
      - ./api/src:/api/src
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
      - PORT=8000
      - KEY=BilbliographyGenerateKey
      - DB_HOST=db
    networks:
      - bibliography-network
    depends_on:
      - db

  frontend:
    image: bibliography-dev-front
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: pdfgenerator-frontend
    environment:
      - REACT_APP_API=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./front/src:/front/src
      - ./front/public:/front/public
    ports:
      - 3000:3000
    networks:
      - bibliography-network
